USE [master]
GO
/****** Object:  Database [EBILL]    Script Date: 08/17/2018 11:32:23 ******/
CREATE DATABASE [EBILL] ON  PRIMARY 
( NAME = N'EBILL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MYSQLEXPRESS\MSSQL\DATA\EBILL.mdf' , SIZE = 3096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EBILL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MYSQLEXPRESS\MSSQL\DATA\EBILL_log.ldf' , SIZE = 15360KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [EBILL] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EBILL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EBILL] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [EBILL] SET ANSI_NULLS OFF
GO
ALTER DATABASE [EBILL] SET ANSI_PADDING OFF
GO
ALTER DATABASE [EBILL] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [EBILL] SET ARITHABORT OFF
GO
ALTER DATABASE [EBILL] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [EBILL] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [EBILL] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [EBILL] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [EBILL] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [EBILL] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [EBILL] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [EBILL] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [EBILL] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [EBILL] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [EBILL] SET  DISABLE_BROKER
GO
ALTER DATABASE [EBILL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [EBILL] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [EBILL] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [EBILL] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [EBILL] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [EBILL] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [EBILL] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [EBILL] SET  READ_WRITE
GO
ALTER DATABASE [EBILL] SET RECOVERY FULL
GO
ALTER DATABASE [EBILL] SET  MULTI_USER
GO
ALTER DATABASE [EBILL] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [EBILL] SET DB_CHAINING OFF
GO
USE [EBILL]
GO
/****** Object:  Table [dbo].[User]    Script Date: 08/17/2018 11:32:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[User](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](250) NOT NULL,
	[Login] [varchar](50) NOT NULL,
	[Password] [varchar](50) NOT NULL,
	[isAdmin] [varchar](10) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Equipment]    Script Date: 08/17/2018 11:32:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Equipment](
	[ID] [varchar](50) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Price] [int] NULL,
 CONSTRAINT [PK_Equipment] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Eqp_Attr]    Script Date: 08/17/2018 11:32:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Eqp_Attr](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Bill_ID] [int] NOT NULL,
	[Equipment_ID] [varchar](50) NOT NULL,
	[Equipment_Quantity] [int] NOT NULL,
 CONSTRAINT [PK_Eqp_Attr] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Bill_Images]    Script Date: 08/17/2018 11:32:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Bill_Images](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Bill_ID] [int] NOT NULL,
	[Image_Url] [varchar](250) NOT NULL,
 CONSTRAINT [PK_Bill_Images] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Bill]    Script Date: 08/17/2018 11:32:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bill](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[createdBy] [int] NOT NULL,
	[createdOn] [date] NOT NULL,
 CONSTRAINT [PK_Bill] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
